import React from "react";

export const ComplianceBadgesSection: React.FC = () => {
  const badges = [
    {
      code: "29100",
      title: "ISO/IEC 29100 – Privacy Framework",
      desc: "Defines 11 internationally accepted privacy principles, providing a structured foundation for personal data protection across digital ecosystems."
    },
    {
      code: "27017",
      title: "ISO/IEC 27017 – Cloud Security Guidelines",
      desc: "Provides security controls and implementation advice specifically for cloud service providers and cloud customers."
    },
    {
      code: "27018",
      title: "ISO/IEC 27018 – Protection of PII in Cloud",
      desc: "Focuses on safeguarding Personally Identifiable Information (PII) in cloud environments following globally recognized privacy practices."
    },
    {
      code: "27557",
      title: "ISO/IEC 27557 – Responsible AI Governance",
      desc: "Establishes principles for trustworthy, transparent, and accountable AI systems aligned with global ethical and governance standards."
    }
  ];

  return (
    <section className="py-20 px-6 md:px-12 bg-[#0d1117] text-white">
      <div className="max-w-7xl mx-auto text-center">

        {/* TITLE */}
        <h2 className="text-4xl font-bold mb-6 bg-gradient-to-r from-blue-400 to-blue-200 bg-clip-text text-transparent">
          Hyper One — International Compliance Standards
        </h2>

        {/* SUBTITLE */}
        <p className="text-gray-300 max-w-3xl mx-auto mb-16 leading-relaxed">
          Hyper One aligns with four internationally recognized ISO/IEC frameworks,
          covering privacy protection, cloud security, personal data handling,
          and responsible AI governance. These standards serve as the ethical and
          operational backbone for the Hyper One ecosystem.
        </p>

        {/* GRID 4 BADGES */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-10">
          {badges.map((item) => (
            <div
              key={item.code}
              className="bg-[#161b22] border border-[#2a2f36] rounded-xl p-6 shadow-md hover:-translate-y-1 hover:shadow-blue-500/30 transition-all"
            >
              {/* BADGE GENERATED BY HTML & CSS */}
              <div className="relative w-28 h-28 mx-auto mb-4 flex items-center justify-center">
                <div
                  className="
                    absolute inset-0 rounded-full 
                    bg-gradient-to-r from-blue-300 to-blue-600
                    opacity-20 blur-lg
                  "
                />

                <div
                  className="
                    w-28 h-28 rounded-full border-2 border-blue-400
                    flex items-center justify-center 
                    text-blue-400 text-xl font-bold
                    bg-[#0d1117]
                  "
                >
                  {item.code}
                </div>
              </div>

              {/* TITLE */}
              <h3 className="text-lg font-semibold text-gray-100 mb-2">
                {item.title}
              </h3>

              {/* DESCRIPTION */}
              <p className="text-sm text-gray-300 leading-relaxed">
                {item.desc}
              </p>
            </div>
          ))}
        </div>

      </div>
    </section>
  );
};
