import React from "react";
import { useLanguage } from "../../context/LanguageContext";  // 🔥 SỬA Ở ĐÂY


export const ComplianceBadgesSection: React.FC = () => {
  const { t, lang } = useLanguage();
  const badges = t("compliance_badges");

  return (
    <section className="py-20 px-6 md:px-12 bg-[#0d1117] text-white">
      <div className="max-w-6xl mx-auto text-center">

        {/* TITLE */}
        <h2 className="text-4xl font-bold mb-6 bg-gradient-to-r from-blue-400 to-blue-200 bg-clip-text text-transparent">
          {t("compliance_title")}
        </h2>

        {/* SUBTITLE */}
        <p className="text-gray-300 max-w-2xl mx-auto mb-12 leading-relaxed">
          {t("compliance_subtitle")}
        </p>

        {/* GRID */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-8">

          {Object.entries(badges).map(([code, item]: any) => (
            <div
              key={code}
              className="bg-[#161b22] border border-[#2a2f36] rounded-xl p-6 shadow-md hover:-translate-y-1 hover:shadow-blue-500/30 transition-all"
            >
              {/* BADGE GENERATED BY HTML & CSS */}
              <div className="relative w-28 h-28 mx-auto mb-4 flex items-center justify-center">
                <div className="
                  absolute inset-0 rounded-full 
                  bg-gradient-to-r from-blue-300 to-blue-600
                  opacity-20 blur-lg
                " />

                <div className="
                  w-28 h-28 rounded-full border-2 border-blue-400
                  flex items-center justify-center 
                  text-blue-400 text-xl font-bold
                  bg-[#0d1117]
                ">
                  {code}
                </div>
              </div>

              {/* TITLE */}
              <h3 className="text-lg font-semibold text-gray-100 mb-2">
                {item.title}
              </h3>

              {/* DESCRIPTION */}
              <p className="text-sm text-gray-300">
                {item.description}
              </p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};
